version: '3.8'

services:
  auth_service:
    build:
      context: ./auth_service
    ports:
      - "8000:8000"
    networks:
      - app-network

  project_service:
    build:
      context: ./project_service
    ports:
      - "8001:8001"
    depends_on:
      - auth_service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
